import { NextResponse } from "next/server";
import { verifyAuth } from "@/lib/auth/verify";
import { createServiceClient } from "@/lib/supabase/server";
import { getPrivyUserInfo } from "@/lib/privy/user-info";

/**
 * POST /api/user/register
 *
 * Creates a minimal user record immediately after first login.
 * Idempotent — safe to call multiple times (returns existing user if already registered).
 * The database trigger `generate_wavcash_id()` auto-generates the WavCash ID on INSERT.
 *
 * If the client doesn't provide a wallet_address, we fetch it server-side from Privy.
 */
export async function POST(request: Request) {
  try {
    const { userId } = await verifyAuth();
    const body = await request.json().catch(() => ({}));
    const supabase = await createServiceClient();

    // Fetch wallet, email, phone from Privy (client wallet takes priority)
    const privyInfo = await getPrivyUserInfo(userId);
    const walletAddress = body.wallet_address || privyInfo.walletAddress;

    // Check if user already exists
    const { data: existing } = await supabase
      .from("users")
      .select("id, wavcash_id, wallet_address, email, phone")
      .eq("id", userId)
      .single();

    if (existing) {
      // User already registered — backfill any missing fields
      const patch: Record<string, unknown> = {};
      if (!existing.wallet_address && walletAddress) patch.wallet_address = walletAddress;
      if (!existing.email && privyInfo.email) patch.email = privyInfo.email;
      if (!existing.phone && privyInfo.phone) patch.phone = privyInfo.phone;

      if (Object.keys(patch).length > 0) {
        await supabase.from("users").update(patch).eq("id", userId);
        return NextResponse.json({ ...existing, ...patch });
      }
      return NextResponse.json(existing);
    }

    // New user — create minimal record
    // Provide defaults for NOT NULL columns (display_name, country, role)
    // so the INSERT succeeds even before onboarding is completed.
    // WavCash ID will be auto-generated by the `set_wavcash_id` trigger.
    const { data, error } = await supabase
      .from("users")
      .insert({
        id: userId,
        display_name: "",
        country: "",
        role: "artist",
        wallet_address: walletAddress || null,
        email: privyInfo.email,
        phone: privyInfo.phone,
      })
      .select()
      .single();

    if (error) {
      // Handle race condition: if another request created the user between our check and insert
      if (error.code === "23505") {
        const { data: raceUser } = await supabase
          .from("users")
          .select("id, wavcash_id, wallet_address")
          .eq("id", userId)
          .single();
        return NextResponse.json(raceUser);
      }
      console.error("User register INSERT failed:", error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(data, { status: 201 });
  } catch {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
}
