import { NextResponse } from "next/server";
import { getResendClient } from "@/lib/email/client";
import { createServiceClient } from "@/lib/supabase/server";
import {
  buildAcknowledgmentEmailHtml,
  buildAcknowledgmentEmailText,
} from "@/lib/email/templates/data-request";

/**
 * POST /api/email/inbound
 *
 * Resend webhook handler for inbound emails.
 * Triggered when someone emails privacy@noreply.wav.cash (forwarded from privacy@wav.cash).
 *
 * Flow:
 * 1. Verify webhook signature
 * 2. Only process `email.received` events to privacy@noreply.wav.cash
 * 3. Fetch full email body via Resend Received Emails API
 * 4. Insert into `data_requests` table
 * 5. Send acknowledgment email back to sender
 */
export async function POST(request: Request) {
  try {
    const resend = getResendClient();
    const secret = process.env.RESEND_WEBHOOK_SECRET;

    if (!secret) {
      console.error("RESEND_WEBHOOK_SECRET not configured");
      return NextResponse.json({ error: "Server misconfigured" }, { status: 500 });
    }

    const rawBody = await request.text();

    // Verify webhook signature
    let event;
    try {
      event = resend.webhooks.verify({
        payload: rawBody,
        headers: {
          id: request.headers.get("svix-id") || "",
          timestamp: request.headers.get("svix-timestamp") || "",
          signature: request.headers.get("svix-signature") || "",
        },
        webhookSecret: secret,
      });
    } catch (err) {
      console.error("Webhook signature verification failed:", err);
      return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
    }

    // Only process inbound email events
    if (event.type !== "email.received") {
      return NextResponse.json({ ok: true, skipped: true });
    }

    const { email_id, from, to, subject } = event.data;

    // Only process emails sent to privacy@noreply.wav.cash
    const isPrivacyEmail = to.some((addr: string) =>
      addr.toLowerCase().includes("privacy@noreply.wav.cash")
    );
    if (!isPrivacyEmail) {
      return NextResponse.json({ ok: true, skipped: true });
    }

    // Fetch full email body via Resend Received Emails API
    let emailBody = "";
    try {
      const fullEmail = await resend.emails.receiving.get(email_id);
      if (fullEmail.data) {
        emailBody = fullEmail.data.text || fullEmail.data.html || "";
      }
    } catch (err) {
      console.error("Failed to fetch email body:", err);
      // Non-critical — continue with empty body
    }

    // Parse sender name from "From" field (e.g. "John Doe <john@example.com>" → "John Doe")
    const senderEmail = extractEmail(from);
    const senderName = extractName(from);

    // Insert into data_requests (reference auto-generated by DB trigger)
    const supabase = await createServiceClient();
    const { data: inserted, error: insertError } = await supabase
      .from("data_requests")
      .insert({
        sender_email: senderEmail,
        sender_name: senderName || null,
        original_subject: subject || null,
        original_body: emailBody || null,
        resend_email_id: email_id,
      })
      .select("reference")
      .single();

    if (insertError) {
      console.error("Failed to insert data request:", insertError);
      return NextResponse.json({ error: "Failed to log request" }, { status: 500 });
    }

    // Send acknowledgment email
    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    try {
      await resend.emails.send({
        from: "WavCash Privacy <privacy@noreply.wav.cash>",
        to: senderEmail,
        subject: "We received your data rights request — WavCash",
        html: buildAcknowledgmentEmailHtml({
          name: senderName || "there",
          date: today,
          requestType: "Data Rights",
          reference: inserted.reference,
        }),
        text: buildAcknowledgmentEmailText({
          name: senderName || "there",
          date: today,
          requestType: "Data Rights",
          reference: inserted.reference,
        }),
      });
    } catch (err) {
      console.error("Failed to send acknowledgment email:", err);
      // Non-critical — the request is still logged
    }

    return NextResponse.json({ ok: true, reference: inserted.reference });
  } catch (err) {
    console.error("Inbound email webhook error:", err);
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}

/** Extract email address from a "Name <email>" or plain "email" string. */
function extractEmail(from: string): string {
  const match = from.match(/<([^>]+)>/);
  return match ? match[1] : from.trim();
}

/** Extract display name from a "Name <email>" string. */
function extractName(from: string): string {
  const match = from.match(/^(.+?)\s*<[^>]+>/);
  return match ? match[1].replace(/^["']|["']$/g, "").trim() : "";
}
