/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WavCashSplitInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR"
      | "SIGN_TYPEHASH"
      | "_executeTokenTransfer"
      | "admin"
      | "collectFees"
      | "collectTokenFees"
      | "distributeAll"
      | "distributeAllToken"
      | "feeBasisPoints"
      | "feeRecipient"
      | "filledSlots"
      | "getPayees"
      | "getSlot"
      | "pendingFees"
      | "pendingTokenFees"
      | "registerSigner"
      | "releasable"
      | "releasableToken"
      | "shares"
      | "slots"
      | "state"
      | "totalFeesCollected"
      | "totalReleased"
      | "totalSlots"
      | "totalTokenFeesCollected"
      | "void_"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DistributionFailed"
      | "FeeCollected"
      | "PaymentReceived"
      | "PaymentReleased"
      | "SlotSigned"
      | "SplitActivated"
      | "SplitVoided"
      | "TokenDistributionFailed"
      | "TokenFeeCollected"
      | "TokenPaymentReleased"
      | "WavCashAction"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGN_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_executeTokenTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectTokenFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeAllToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "filledSlots",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPayees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSlot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTokenFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSigner",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasableToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "shares", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "slots", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSlots",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokenFeesCollected",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "void_", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGN_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_executeTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTokenFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeAllToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledSlots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSlot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTokenFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "releasable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasableToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalSlots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalTokenFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "void_", data: BytesLike): Result;
}

export namespace DistributionFailedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReceivedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlotSignedEvent {
  export type InputTuple = [
    slotIndex: BigNumberish,
    signer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    slotIndex: bigint,
    signer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    slotIndex: bigint;
    signer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitActivatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitVoidedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDistributionFailedEvent {
  export type InputTuple = [
    token: AddressLike,
    account: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, account: string, amount: bigint];
  export interface OutputObject {
    token: string;
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFeeCollectedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenPaymentReleasedEvent {
  export type InputTuple = [
    token: AddressLike,
    account: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, account: string, amount: bigint];
  export interface OutputObject {
    token: string;
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WavCashActionEvent {
  export type InputTuple = [action: string];
  export type OutputTuple = [action: string];
  export interface OutputObject {
    action: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WavCashSplit extends BaseContract {
  connect(runner?: ContractRunner | null): WavCashSplit;
  waitForDeployment(): Promise<this>;

  interface: WavCashSplitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  SIGN_TYPEHASH: TypedContractMethod<[], [string], "view">;

  _executeTokenTransfer: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  collectFees: TypedContractMethod<[], [void], "nonpayable">;

  collectTokenFees: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  distributeAll: TypedContractMethod<[], [void], "nonpayable">;

  distributeAllToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  feeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  filledSlots: TypedContractMethod<[], [bigint], "view">;

  getPayees: TypedContractMethod<[], [string[]], "view">;

  getSlot: TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, string, bigint] & {
        sharesBps: bigint;
        signer: string;
        signedAt: bigint;
      }
    ],
    "view"
  >;

  pendingFees: TypedContractMethod<[], [bigint], "view">;

  pendingTokenFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  registerSigner: TypedContractMethod<
    [
      slotIndex: BigNumberish,
      signer: AddressLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  releasable: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  releasableToken: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  shares: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  slots: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint] & {
        sharesBps: bigint;
        signer: string;
        signedAt: bigint;
      }
    ],
    "view"
  >;

  state: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  totalSlots: TypedContractMethod<[], [bigint], "view">;

  totalTokenFeesCollected: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  void_: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SIGN_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_executeTokenTransfer"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectTokenFees"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeAllToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "filledSlots"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayees"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSlot"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [bigint, string, bigint] & {
        sharesBps: bigint;
        signer: string;
        signedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingTokenFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerSigner"
  ): TypedContractMethod<
    [
      slotIndex: BigNumberish,
      signer: AddressLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releasable"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "releasableToken"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "shares"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "slots"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint] & {
        sharesBps: bigint;
        signer: string;
        signedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSlots"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTokenFeesCollected"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "void_"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DistributionFailed"
  ): TypedContractEvent<
    DistributionFailedEvent.InputTuple,
    DistributionFailedEvent.OutputTuple,
    DistributionFailedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReceived"
  ): TypedContractEvent<
    PaymentReceivedEvent.InputTuple,
    PaymentReceivedEvent.OutputTuple,
    PaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "SlotSigned"
  ): TypedContractEvent<
    SlotSignedEvent.InputTuple,
    SlotSignedEvent.OutputTuple,
    SlotSignedEvent.OutputObject
  >;
  getEvent(
    key: "SplitActivated"
  ): TypedContractEvent<
    SplitActivatedEvent.InputTuple,
    SplitActivatedEvent.OutputTuple,
    SplitActivatedEvent.OutputObject
  >;
  getEvent(
    key: "SplitVoided"
  ): TypedContractEvent<
    SplitVoidedEvent.InputTuple,
    SplitVoidedEvent.OutputTuple,
    SplitVoidedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDistributionFailed"
  ): TypedContractEvent<
    TokenDistributionFailedEvent.InputTuple,
    TokenDistributionFailedEvent.OutputTuple,
    TokenDistributionFailedEvent.OutputObject
  >;
  getEvent(
    key: "TokenFeeCollected"
  ): TypedContractEvent<
    TokenFeeCollectedEvent.InputTuple,
    TokenFeeCollectedEvent.OutputTuple,
    TokenFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "TokenPaymentReleased"
  ): TypedContractEvent<
    TokenPaymentReleasedEvent.InputTuple,
    TokenPaymentReleasedEvent.OutputTuple,
    TokenPaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "WavCashAction"
  ): TypedContractEvent<
    WavCashActionEvent.InputTuple,
    WavCashActionEvent.OutputTuple,
    WavCashActionEvent.OutputObject
  >;

  filters: {
    "DistributionFailed(address,uint256)": TypedContractEvent<
      DistributionFailedEvent.InputTuple,
      DistributionFailedEvent.OutputTuple,
      DistributionFailedEvent.OutputObject
    >;
    DistributionFailed: TypedContractEvent<
      DistributionFailedEvent.InputTuple,
      DistributionFailedEvent.OutputTuple,
      DistributionFailedEvent.OutputObject
    >;

    "FeeCollected(uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "PaymentReceived(address,uint256)": TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;
    PaymentReceived: TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;

    "PaymentReleased(address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "SlotSigned(uint256,address,uint256)": TypedContractEvent<
      SlotSignedEvent.InputTuple,
      SlotSignedEvent.OutputTuple,
      SlotSignedEvent.OutputObject
    >;
    SlotSigned: TypedContractEvent<
      SlotSignedEvent.InputTuple,
      SlotSignedEvent.OutputTuple,
      SlotSignedEvent.OutputObject
    >;

    "SplitActivated(uint256)": TypedContractEvent<
      SplitActivatedEvent.InputTuple,
      SplitActivatedEvent.OutputTuple,
      SplitActivatedEvent.OutputObject
    >;
    SplitActivated: TypedContractEvent<
      SplitActivatedEvent.InputTuple,
      SplitActivatedEvent.OutputTuple,
      SplitActivatedEvent.OutputObject
    >;

    "SplitVoided(uint256)": TypedContractEvent<
      SplitVoidedEvent.InputTuple,
      SplitVoidedEvent.OutputTuple,
      SplitVoidedEvent.OutputObject
    >;
    SplitVoided: TypedContractEvent<
      SplitVoidedEvent.InputTuple,
      SplitVoidedEvent.OutputTuple,
      SplitVoidedEvent.OutputObject
    >;

    "TokenDistributionFailed(address,address,uint256)": TypedContractEvent<
      TokenDistributionFailedEvent.InputTuple,
      TokenDistributionFailedEvent.OutputTuple,
      TokenDistributionFailedEvent.OutputObject
    >;
    TokenDistributionFailed: TypedContractEvent<
      TokenDistributionFailedEvent.InputTuple,
      TokenDistributionFailedEvent.OutputTuple,
      TokenDistributionFailedEvent.OutputObject
    >;

    "TokenFeeCollected(address,uint256)": TypedContractEvent<
      TokenFeeCollectedEvent.InputTuple,
      TokenFeeCollectedEvent.OutputTuple,
      TokenFeeCollectedEvent.OutputObject
    >;
    TokenFeeCollected: TypedContractEvent<
      TokenFeeCollectedEvent.InputTuple,
      TokenFeeCollectedEvent.OutputTuple,
      TokenFeeCollectedEvent.OutputObject
    >;

    "TokenPaymentReleased(address,address,uint256)": TypedContractEvent<
      TokenPaymentReleasedEvent.InputTuple,
      TokenPaymentReleasedEvent.OutputTuple,
      TokenPaymentReleasedEvent.OutputObject
    >;
    TokenPaymentReleased: TypedContractEvent<
      TokenPaymentReleasedEvent.InputTuple,
      TokenPaymentReleasedEvent.OutputTuple,
      TokenPaymentReleasedEvent.OutputObject
    >;

    "WavCashAction(string)": TypedContractEvent<
      WavCashActionEvent.InputTuple,
      WavCashActionEvent.OutputTuple,
      WavCashActionEvent.OutputObject
    >;
    WavCashAction: TypedContractEvent<
      WavCashActionEvent.InputTuple,
      WavCashActionEvent.OutputTuple,
      WavCashActionEvent.OutputObject
    >;
  };
}
